#!/bin/sh
export ZOOKEEPER_CLIENT_PORT=2181
export ZOOKEEPER_TICK_TIME=2000
export KAFKA_BROKER_ID=1
export KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://server:9092,PLAINTEXT_HOST://server:9092
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
export KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
systemctl start zookeeper
systemctl start kafka
